# Generated by Django 5.2.5 on 2025-08-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dropoff_location',
            field=models.CharField(choices=[('Abington', 'Abington'), ('Norton', 'Norton'), ('Saugus', 'Saugus'), ('Framingham', 'Framingham')], default='Abington', help_text='Select your preferred dropoff location', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter phone number (e.g., +1-555-123-4567)', max_length=15, null=True),
        ),
    ]
