# Generated by Django 5.2.5 on 2025-08-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_profile_dropoff_location_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_choice',
            field=models.CharField(choices=[('cash_40', '40% of sale value in cash'), ('credit_70', '70% of sale value in store credit')], default='credit_70', help_text='Select your preferred payment method', max_length=20),
        ),
    ]
