# Generated by Django 5.2.5 on 2025-08-31 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_login_attempt', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Honeypot Attempt',
                'verbose_name_plural': 'Honeypot Attempts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
