# Generated by Django 5.2.5 on 2025-08-31 02:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the game', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the game (minimum $0.01)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('condition', models.CharField(choices=[('new in shrink', 'New in Shrink - Original shrinkwrap/seal is intact. Never Opened'), ('like new', 'Like New - Pieces unpunched, cards wrapped, never played'), ('very good', 'Very Good - Pieces punched, Sorted. Rarely or never played. No discernible wear'), ('good', 'Good - Played but well maintained. Pieces unsorted. Box/book(s) shows signs of use'), ('fair', 'Fair - Discernible wear. Box/book(s) shows minor damage and/or have been slightly marked'), ('poor', 'Poor - Worn but playable. Box/book(s) shows damage and/or have been significantly marked')], default='good', help_text='Select the condition of the game', max_length=20)),
                ('missing_pieces', models.BooleanField(default=False, help_text='Check if the game has missing pieces')),
                ('description_of_missing_pieces', models.TextField(blank=True, help_text='Describe what pieces are missing (e.g., "Missing 2 red dice and instruction manual")', null=True)),
                ('smoking_house', models.BooleanField(default=False, help_text='Check if the game has been exposed to smoke from a smoking household')),
                ('musty_smell', models.BooleanField(default=False, help_text='Check if the game has a musty or unpleasant odor')),
                ('pet', models.CharField(choices=[('none', 'None'), ('cat', 'Cat'), ('dog', 'Dog')], default='none', help_text='Select if the game has been exposed to pets', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this game', on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-created_at'],
            },
        ),
    ]
