# Generated by Django 5.2.5 on 2025-08-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='printed',
            field=models.BooleanField(default=False, help_text='Check if the game is a printed/custom version'),
        ),
    ]
