# Generated by Django 5.2.5 on 2025-09-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='received',
            field=models.BooleanField(default=False, help_text='Check if the game has been received by the store (admin only)'),
        ),
    ]
