# Generated by Django 5.2.5 on 2025-09-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='received_date',
            field=models.DateTimeField(blank=True, help_text='Date when the game was received by the store (admin only)', null=True),
        ),
    ]
